# This is a basic workflow to help you get started with Actions

name: lksj

# Controls when the workflow will run
on:
  workflow_dispatch:
   inputs:
     auth:
        description: 'Google Remote Desktop Command'
        default: ''
        required: true
     pin:
        description: 'PIN'
        default: '123456'
        required: true
     chrome:
        description: |
          [boolean] Choose one
        default: true
        required: false
defaults:
  run:
    shell: bash
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: 'Set up a Ubuntu machine'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Add User
      run: |
        sudo useradd -m brooke
        sudo adduser brooke sudo
        echo 'brooke:Jacobs123' | sudo chpasswd
        sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd
    - name: Install
      run: |
         wget https://raw.githubusercontent.com/jemuk02/mqkq/main/install.sh
         sudo chmod +x ./install.sh
         sudo ./install.sh
    - name: Run RD command
      run: "${{ github.event.inputs.auth }} --pin=${{ github.event.inputs.pin }}"
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
